### ISSUE TITLE
something broke with d3?

### ISSUE THREAD

**Issue by DevinBayly** [arken/arken.github.io#3]
In trying to see what the exports error was that you had I got setup with your instructions and then ran into this

```
> svelte-app@1.0.0 dev /place/arken.github.io/static/graphic
> rollup -c -w

rollup v2.18.2
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /place/arken.github.io/static/graphic/node_modules/d3/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /place/arken.github.io/static/graphic/node_modules/d3/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.requireRelative.resolve (/place/arken.github.io/static/graphic/node_modules/require-relative/index.js:30:17)
    at tryResolve (/place/arken.github.io/static/graphic/node_modules/rollup-plugin-svelte/index.js:50:19)
    at Object.resolveId (/place/arken.github.io/static/graphic/node_modules/rollup-plugin-svelte/index.js:177:21)
    at /place/arken.github.io/static/graphic/node_modules/rollup/dist/shared/rollup.js:18215:25

```

Is this the same as what you're seeing?

**Comment by alecbcs** [comment]
Fixed!
